name = "d1-event-scheduler-dev"
main = "src/index.ts"
compatibility_date = "2024-03-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
# route = { pattern = "event-scheduler.example.com", custom_domain = true }
minify = true
durable_objects.bindings = [
    { name = "D1_EVENT_SCHEDULER", class_name = "D1EventScheduler" },
]
migrations = [{ tag = "v1", new_classes = ["D1EventScheduler"] }]
d1_databases = [
    # { binding = "DB", database_name = "EXAMPLE", database_id = "example-db-id-goes-here", preview_database_id = "example-db-id-goes-here" },
]

[placement]
mode = "smart"

[env.production]
name = "d1-event-scheduler"
compatibility_date = "2024-03-04"
compatibility_flags = ["nodejs_compat"]
route = { pattern = "event-scheduler.d1.demosjarco.dev", custom_domain = true }
durable_objects.bindings = [
    { name = "D1_EVENT_SCHEDULER", class_name = "D1EventScheduler" },
]
migrations = [{ tag = "v1", new_classes = ["D1EventScheduler"] }]
d1_databases = [
    # { binding = "DB", database_name = "EXAMPLE", database_id = "example-db-id-goes-here", preview_database_id = "example-db-id-goes-here" },
]

[env.production.placement]
mode = "smart"
