export interface DefinedEvent {}

export enum EventDetailsKeys {
	D1_BINDING = 'EVENT_SCHEMA',
	EVENT_NAME = 'EVENT_NAME',
	DEFINER = 'DEFINER',
	TIME_ZONE = 'TIME_ZONE',
	EVENT_DEFINITION = 'EVENT_DEFINITION',
	EVENT_TYPE = 'EVENT_TYPE',
	EXECUTE_AT = 'EXECUTE_AT',
	INTERVAL_VALUE = 'INTERVAL_VALUE',
}
