name: Auto Dependabot
on: pull_request

permissions:
  contents: read

jobs:
  enhance:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
    steps:
      - uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: dependabot/fetch-metadata@5e5f99653a5b510e8555840e80cbf1514ad4af38 # v2.1.0
        id: dependabot-metadata
      - run: echo "SEMVER_UPDATE=$(echo "${{ steps.dependabot-metadata.outputs.update-type }}" | cut -d':' -f2)" >> "$GITHUB_OUTPUT"
        id: dependabot-metadata-update-type
      - run: gh pr edit "${{ github.event.pull_request.html_url }}" --add-label "${{ steps.dependabot-metadata-update-type.outputs.SEMVER_UPDATE }}"
        env:
          GH_TOKEN: ${{ github.token }}
  automate:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: dependabot/fetch-metadata@5e5f99653a5b510e8555840e80cbf1514ad4af38 # v2.1.0
        id: dependabot-metadata
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - run: gh pr checkout "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
        if: steps.dependabot-metadata.outputs.dependency-group == 'typescript-types' || steps.dependabot-metadata.outputs.dependency-group == 'code-management'
        env:
          GH_TOKEN: ${{ github.token }}
