name: Format Code

on:
  push:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.mjs'
      - '**.cjs'
      - '**.ts'
      - '**.tsx'
      - '**.mts'
      - '**.cts'
      - '**.css'
      - '**.less'
      - '**.scss'
      - '**.html'
      - '**.hbs'
      - '**.json'
      - '**.gql'
      - '**.graphql'
      - '**.md'
      - '**.mdx'
      - '**.yaml'
      - '**.yml'
  pull_request:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.mjs'
      - '**.cjs'
      - '**.ts'
      - '**.tsx'
      - '**.mts'
      - '**.cts'
      - '**.css'
      - '**.less'
      - '**.scss'
      - '**.html'
      - '**.hbs'
      - '**.json'
      - '**.gql'
      - '**.graphql'
      - '**.md'
      - '**.mdx'
      - '**.yaml'
      - '**.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci
      - run: npm run fmt
      - name: Check for Changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      - name: Git Setup
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git commit -am "Ran formatter"
        if: steps.changes.outputs.changes == 'true'
      - run: git push
        if: steps.changes.outputs.changes == 'true'
