name: Update `workerd` runtime

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**/package*.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  update-toml:
    if: github.event_name == 'workflow_dispatch' || (startsWith(github.event.pull_request.head.ref, 'dependabot/npm_and_yarn/') && contains(github.event.pull_request.head.ref, '/cloudflare-') && github.actor == 'dependabot[bot]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          disable-sudo: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci
      # No need to run `npm ci` in submodule
      - name: Get minor version of workerd
        id: get-version
        run: |
          VERSION=$(npm ls workerd --json | jq -r '.. | .workerd?.version? | select(.)')
          MINOR_VERSION=${VERSION#*.}
          MINOR_VERSION_HYPHEN="${MINOR_VERSION:0:4}-${MINOR_VERSION:4:2}-${MINOR_VERSION:6:2}"
          echo "minor-version-hyphen=$MINOR_VERSION_HYPHEN" >> $GITHUB_OUTPUT
      - name: Update `compatibility_date`
        run: find . -maxdepth 2 -name "wrangler.toml" -print0 | xargs -0 sed -i "/compatibility_date = .*/s//compatibility_date = \"${{ steps.get-version.outputs.minor-version-hyphen }}\"/"
      - name: Git Setup
        run: |
          git config user.name "dependabot[bot]"
          git config user.email "dependabot[bot]@users.noreply.github.com"
      - run: find . -maxdepth 2 -name "wrangler.toml" -print0 | xargs -0 git add
      - run: git commit -m "Update \`compatibility_date\` in \`wrangler.toml\`" || echo "`compatibility_date` already up to date"
      - run: git push
